### ISSUE TITLE
Namaste Nirav !

### ISSUE THREAD

**Issue by adi-g15** [niravcodes/Sakshyar#1]
Namaste @niravcodes, I am Aditya, a btech student from NIT Patna, India.
We had a course on compiler design this semester, so just as a hobby project -> https://github.com/adi-g15/saras we started creating a compiler frontend, that also supports writing programs in Hindi, rest logic parts are similar to LLVM's tutorial actually. ( It is just a fun hobby project )

I happened to reach your blog somehow, and then your github from there, then some individual projects, and some questions :sweat_smile: 
1. What do you use to directly type programs in Hindi, i really want to know, there was software that i used to on windows (as in a screenshot in one of the blogs)
2. Is Sakshyar also something on that line as i wrote above
3. And, in case you want i can transfer or add collaborator to the project (again, hobby project nothing serious only if you want)
4. What do you suggest hindi keywords for keywords like if, else, then etc. :sweat_smile:  ?

Currently I am trying to successfully compile this (about to), I thought these keywords make sense, just an opinion from you ?
![2021-11-21_00-59](https://user-images.githubusercontent.com/37269665/143500876-4cbc0d4b-4230-492e-a381-3ecaf3b32afd.png)

**Comment by niravcodes** [comment]
Hey Adi, good luck on your project. It's a pretty interesting class of project to work on. To answer your questions:

1. To type Devanagari, I made my own (kinda phonetic) keyboard layout [detailed here](https://nirav.com.np/2020/02/07/an-easier-nepali-keyboard-layout.html). You can likely download it and use it with little to no modifications
2. No, for Sakshyar (later renamed (मन्सा)[http://mnsa.cc]) I wrote the entire recursive descent parser, made the AST and generated assembly or C++ from it, all from scratch.
3. I'm terribly busy so collaboration is impossible for now. I haven't even had the time to clean up the code and opensource the compiler. If you do end up making `saras` do shoot me an email tho. I'd love to use it.
4. I def don't understand enough hindi to recommend keywords. Try to find something that most people understand.

**Comment by adi-g15** [comment]
> 

Thanks for the answers Nirav, will try it, also that keyboard layout thing clicked an idea in my mind, i guess will try someday to 'create' my own if that's possible, your blog and project are interesting btw :smile:
